### ISSUE TITLE
有发布的打包版本吗？

### ISSUE THREAD

**Issue by wuyilingwei** [Baka632/ArknightsStoryText.UWP#1]
（路过）

**Comment by Baka632** [comment]
刚刚发了一个（

[Release 1.0.9.0](https://github.com/Baka632/ArknightsStoryText.UWP/releases/tag/1.0.9.0)

**Comment by wuyilingwei** [comment]
直接闪退力（悲）

**Comment by Baka632** [comment]
你的系统版本是多少呢？

**Comment by wuyilingwei** [comment]
版本        Windows 11 专业版
版本        22H2
安装日期      2022/11/10
操作系统版本    22621.1702
体验        Windows 功能体验包 1000.22641.1000.0

**Comment by wuyilingwei** [comment]
https://github.com/yige-yigeren/MagiskOnWSAAuto
来都来了顺便帮忙点个star呗

**Comment by Baka632** [comment]
我这里是没有问题的...
![image](https://github.com/Baka632/ArknightsStoryText.UWP/assets/48171809/41a99dc0-a11a-4409-b1b6-6fe8cdf6b9c6)

**Comment by wuyilingwei** [comment]
[guide_act38d1_entry.txt](https://github.com/Baka632/ArknightsStoryText.UWP/files/11888979/guide_act38d1_entry.txt)
哦，我刚才顺手选到尖灭了（）估计尖灭有些不一样

**Comment by Baka632** [comment]
嗯，这是[上游库](https://github.com/ArknightsResources/Utility)的设计缺陷，因为你选择的文件是**教程**文件，目前 ArknightsResources.Utility 库还不支持解析相关的剧情文本。

![image](https://github.com/Baka632/ArknightsStoryText.UWP/assets/48171809/5573bfb1-0e29-4e76-b39e-7676e79b4c41)

**Comment by wuyilingwei** [comment]
> 嗯，这是[上游库](https://github.com/ArknightsResources/Utility)的设计缺陷，因为你选择的文件是**教程**文件，目前 ArknightsResources.Utility 库还不支持解析相关的剧情文本。
> 
> ![image](https://user-images.githubusercontent.com/48171809/249327168-5573bfb1-0e29-4e76-b39e-7676e79b4c41.png)

哦（）我随便挑的，我还说怎么有个38号的act，就随便打开看看，结果是尖灭的教程2333333

**Comment by Baka632** [comment]
> 直接闪退力（悲）

~~版本[2.1.0.0](https://github.com/Baka632/ArknightsStoryText.UWP/releases/tag/2.1.0.0)修复了打开教程文件时的崩溃问题，现在应用会提示不支持而不是直接崩溃。~~

版本[2.2.0.0](https://github.com/Baka632/ArknightsStoryText.UWP/releases/tag/2.2.0.0)进一步增强了应用的错误处理能力，现在应用能够应对大多数错误了。
~~更耐艹了~~
