### ISSUE TITLE
一些未来增强的建议

### ISSUE THREAD

**Issue by wuyilingwei** [Baka632/ArknightsStoryText.UWP#7]
可以打开文件夹功能，这样可以直接打开一整个活动的剧情
选择字体/字号的功能
加入对设置gamedatePath（手动设置/自动检索），然后根据活动和关卡打开的功能

**Comment by Baka632** [comment]
当前进度：
- [x] 打开文件夹 (#10)
- [x] 选择字体/字号 (#8)

~~设置读取gamedata文件夹，然后根据活动和关卡打开的功能~~ (不打算实现)

**Comment by Baka632** [comment]
> 加入对设置gamedatePath（手动设置/自动检索），然后根据活动和关卡打开的功能

目前不打算实现这个功能，因为这需要 gamedata 文件夹及各活动/关卡的描述信息，这项工作对我们来说比较困难。

你还有其它建议吗？如果没有我就关 Issue 了。

**Comment by wuyilingwei** [comment]
> > 加入对设置gamedatePath（手动设置/自动检索），然后根据活动和关卡打开的功能
> 
> 目前不打算实现这个功能，因为这需要 gamedata 文件夹及各活动/关卡的描述信息，这项工作对我们来说比较困难。
> 
> 你还有其它建议吗？如果没有我就关 Issue 了。

嗯，没有了@.@

我提出打开gamedata的主要想法是合并关卡描述/关卡名称，以及该关卡的前后剧情，方便检索与阅读

**Comment by Baka632** [comment]
这样的话，需要对 yj 的 JSON 文件进行解析（如 story_review_table.json），目前我没有进行这项工作的计划。

未来，我们可能会添加这项功能，但需要解决很多问题（例如：如何将 gamedata/story/activities 与gamedata/story/[uc]info/activities 关联）。

不过，这都是后话了。

~~说了这么多，其实就是想摸鱼（乐）~~

**Comment by Baka632** [comment]
当前进度：
- [x] 添加读取剧情元数据的功能 - 第一部分 (#13)

**Comment by Baka632** [comment]
@yige-yigeren 现在已经初步实现了在阅读页与合并页中显示关卡名称的功能了，你可以尝试一下，并给我们提出建议。

这里是测试版地址：[https://github.com/Baka632/ArknightsStoryText.UWP/releases/tag/4.5.2.255]()

关卡描述及剧情检索功能正在开发中。

（PS：请准备好 ```story_review_table.json``` 文件，其位于 ```gamedata/excel``` 文件夹中）

**Comment by wuyilingwei** [comment]
> @yige-yigeren 现在已经初步实现了在阅读页与合并页中显示关卡名称的功能了，你可以尝试一下，并给我们提出建议。
> 
> 这里是测试版地址：https://github.com/Baka632/ArknightsStoryText.UWP/releases/tag/4.5.2.255
> 
> 关卡描述及剧情检索功能正在开发中。
> 
> （PS：请准备好 `story_review_table.json` 文件，其位于 `gamedata/excel` 文件夹中）

版本        Windows 11 专业版
版本        23H2
安装日期      2022/11/10
操作系统版本    22631.2715
体验        Windows 功能体验包 1000.22677.1000.0

加载文件时崩溃
错误应用程序名称: ArknightsStoryText.UWP.exe，版本: 1.0.0.0，时间戳: 0x656f1627
错误模块名称: twinapi.appcore.dll，版本: 10.0.22621.2506，时间戳: 0x72110e26
异常代码: 0xc000027b
错误偏移量: 0x00000000000d0503
错误进程 ID: 0x0x65A4
错误应用程序启动时间: 0x0x1DA278FBC5B7D16
错误应用程序路径: C:\Program Files\WindowsApps\e34e41f8-8622-4faf-9f0b-7b69d6c25374_4.5.2.255_x64__xrr5xv0r1z0t2\ArknightsStoryText.UWP.exe
错误模块路径: C:\Windows\SYSTEM32\twinapi.appcore.dll
报告 ID: 26af8a93-11e2-4933-b26f-14285c1adb6c
错误程序包全名: e34e41f8-8622-4faf-9f0b-7b69d6c25374_4.5.2.255_x64__xrr5xv0r1z0t2
错误程序包相对应用程序 ID: App
~~~
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" Guid="{a0e9b465-b939-57d7-b27d-95d8e925ff57}" /> 
  <EventID>1000</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x8000000000000000</Keywords> 
  <TimeCreated SystemTime="2023-12-05T15:29:11.6961104Z" /> 
  <EventRecordID>86840</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="16200" ThreadID="15696" /> 
  <Channel>Application</Channel> 
  <Computer>Lsy-Pc-2-2</Computer> 
  <Security UserID="S-1-5-21-4045361216-2697596938-2413616667-1002" /> 
  </System>
- <EventData>
  <Data Name="AppName">ArknightsStoryText.UWP.exe</Data> 
  <Data Name="AppVersion">1.0.0.0</Data> 
  <Data Name="AppTimeStamp">656f1627</Data> 
  <Data Name="ModuleName">twinapi.appcore.dll</Data> 
  <Data Name="ModuleVersion">10.0.22621.2506</Data> 
  <Data Name="ModuleTimeStamp">72110e26</Data> 
  <Data Name="ExceptionCode">c000027b</Data> 
  <Data Name="FaultingOffset">00000000000d0503</Data> 
  <Data Name="ProcessId">0x65a4</Data> 
  <Data Name="ProcessCreationTime">0x1da278fbc5b7d16</Data> 
  <Data Name="AppPath">C:\Program Files\WindowsApps\e34e41f8-8622-4faf-9f0b-7b69d6c25374_4.5.2.255_x64__xrr5xv0r1z0t2\ArknightsStoryText.UWP.exe</Data> 
  <Data Name="ModulePath">C:\Windows\SYSTEM32\twinapi.appcore.dll</Data> 
  <Data Name="IntegratorReportId">26af8a93-11e2-4933-b26f-14285c1adb6c</Data> 
  <Data Name="PackageFullName">e34e41f8-8622-4faf-9f0b-7b69d6c25374_4.5.2.255_x64__xrr5xv0r1z0t2</Data> 
  <Data Name="PackageRelativeAppId">App</Data> 
  </EventData>
  </Event>
~~~
这里是我的json文件
[story_review_table.json](https://github.com/Baka632/ArknightsStoryText.UWP/files/13562105/story_review_table.json)

**Comment by Baka632** [comment]
你的 JSON 文件没问题，稍等，我发一个新包

**Comment by Baka632** [comment]
@yige-yigeren 你现在可以卸载掉现在这个版本的应用，因为下一个版本改包名了（）

**Comment by Baka632** [comment]
@yige-yigeren
[最新测试版本](https://github.com/Baka632/ArknightsStoryText.UWP/releases/tag/4.5.2.256)

**Comment by wuyilingwei** [comment]
> @yige-yigeren [最新测试版本](https://github.com/Baka632/ArknightsStoryText.UWP/releases/tag/4.5.2.256)

似乎没有任何问题了

**Comment by Baka632** [comment]
> > @yige-yigeren [最新测试版本](https://github.com/Baka632/ArknightsStoryText.UWP/releases/tag/4.5.2.256)
> 
> 似乎没有任何问题了

草草草，我还没做完呢，你就关 Issue 了（

还有剧情检索没做完呢 qwq

**Comment by wuyilingwei** [comment]
> > > @yige-yigeren [最新测试版本](https://github.com/Baka632/ArknightsStoryText.UWP/releases/tag/4.5.2.256)
> > 
> > 
> > 似乎没有任何问题了
> 
> 草草草，我还没做完呢，你就关 Issue 了（
> 
> 还有剧情检索没做完呢 qwq

半场开香槟了属于是（）

**Comment by Baka632** [comment]
很抱歉，由于我最近学业繁忙（尤其是期末考试），目前我暂时难以进行进一步的开发。

所以我先把已实现的功能合并到主分支，并打包发布，剩下的“剧情检索”功能待之后再说吧。

大概要等到一月份，我才能恢复开发工作（悲）

这是正式版本：[4.5.3.0](https://github.com/Baka632/ArknightsStoryText.UWP/releases/tag/4.5.3.0)

**Comment by Baka632** [comment]
当前进度：
- [x] 添加剧情概览页 - 第二部分 (#14)

**Comment by Baka632** [comment]
@yige-yigeren 现在已经实现读取 ```gamedata``` 文件夹的功能了。
测试版地址：[4.5.3.5](https://github.com/Baka632/ArknightsStoryText.UWP/releases/tag/4.5.3.5)

~~这个拖了五个月的 Issue 终于要 Close 了吗~~

**Comment by Baka632** [comment]
正式版 [4.6.0.0](https://github.com/Baka632/ArknightsStoryText.UWP/releases/tag/4.6.0.0) 已经发布。

这个 Issue 我就关了，如果有新的问题请开新的 Issue。

~~这个拖了五个月的 Issue 终于解决掉了 q(≧▽≦q)~~

**Comment by wuyilingwei** [comment]
> 正式版 [4.6.0.0](https://github.com/Baka632/ArknightsStoryText.UWP/releases/tag/4.6.0.0) 已经发布。
> 
> 这个 Issue 我就关了，如果有新的问题请开新的 Issue。
> 
> ~这个拖了五个月的 Issue 终于解决掉了 q(≧▽≦q)~

好欸

**Comment by wuyilingwei** [comment]
不如直接一步到位自动下游戏gamedata（bushi）
